name: Test

on:
  push:
    branches:
      - '*'
    tags-ignore:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Submodules
      run: git submodule update --init --recursive
    - name: Server
      run: |
        curl https://s3-eu-west-1.amazonaws.com/stremio-artifacts/four/master/server.js > ./server.js
        node server.js &
    - name: Checkout Test Addon
      uses: actions/checkout@v2
      with:
        repository: nklhrstv/stremio-pentest-addon
    - name: Run Test Addon
      run: |
        yarn install
        ./run &
    - name: Test
      run: cargo test
